# Generated by Django 5.2.8 on 2026-01-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('beverage', 'Beverage'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
